#!/usr/bin/env python3
"""Recapture the report screenshot used in the README.

The previous one was taken at 0.0.26 and sat unchanged through the whole report
redesign (#110-#125), so the picture advertising the project showed a design it
no longer had (#151). A screenshot is a claim about the current output like any
other, and this is what re-checks it.

Deliberately *not* wired into `scripts/build_docs_assets.py --check`. That check
compares generated bytes, and a browser screenshot is not byte-reproducible
across platforms, font sets or Chromium builds -- adding it there would buy a
flaky CI job rather than a guarantee. Run this when the design changes.

Usage:
    uv run --with playwright python scripts/capture_report_screenshot.py

Requires Chromium. If Playwright's browser lives somewhere unusual, point at it:
    PYSURICATA_CHROME=/path/to/chrome uv run ... scripts/capture_report_screenshot.py
"""

from __future__ import annotations

import os
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

OUT = REPO_ROOT / "docs" / "assets" / "report-screenshot.png"
SOURCE = REPO_ROOT / "docs" / "assets" / "example_report.html"

#: Wide enough that cards are drawn at their intended proportions rather than a
#: responsive tier, and tall enough to reach the first column card -- the
#: summary alone does not show what the redesign changed.
VIEWPORT = {"width": 1440, "height": 1680}


def _chrome() -> str | None:
    explicit = os.environ.get("PYSURICATA_CHROME")
    if explicit:
        return explicit
    for candidate in pathlib.Path("/opt/pw-browsers").glob(
        "chromium-*/chrome-linux/chrome"
    ):
        return str(candidate)
    return None  # let Playwright resolve its own default


def main() -> int:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print(
            "playwright is not installed. Run with: uv run --with playwright python ..."
        )
        return 2

    if not SOURCE.exists():
        print(f"{SOURCE} is missing. Run scripts/regenerate_example_report.py first.")
        return 2

    launch: dict[str, str] = {}
    chrome = _chrome()
    if chrome:
        launch["executable_path"] = chrome

    with sync_playwright() as p:
        browser = p.chromium.launch(**launch)
        page = browser.new_page(viewport=VIEWPORT)
        page.goto(SOURCE.as_uri())
        # The report builds its charts on load; give it a beat before capturing.
        page.wait_for_timeout(1200)

        # Collapse the sample table. It is ten rows of Titanic passengers and
        # eats the whole fold, so a shot that leaves it open shows the summary
        # and stops at the word "Variables" -- omitting the column cards, which
        # are the part the redesign actually changed and the part worth showing.
        for label in page.query_selector_all("summary, .sample-toggle, button"):
            text = (label.inner_text() or "").strip().lower()
            if text.startswith("hide sample"):
                label.click()
                page.wait_for_timeout(400)
                break

        page.screenshot(path=str(OUT))
        browser.close()

    print(
        f"wrote {OUT.relative_to(REPO_ROOT)} at {VIEWPORT['width']}x{VIEWPORT['height']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
