name: Docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # needed for gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up UV
        uses: astral-sh/setup-uv@v3

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          uv sync --dev
          uv run python -c "import sys;print(sys.version)"

      - name: Build docs
        run: uv run mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages